import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  artworkSidebar: [
    {
      type: 'category',
      label: 'Graphics',
      items: [{type: 'autogenerated', dirName: 'graphics'}],
    },
    {
      type: 'category',
      label: 'Photos',
      items: [{type: 'autogenerated', dirName: 'photos'}],
    },
    {
      type: 'category',
      label: 'Reliefs',
      items: [{type: 'autogenerated', dirName: 'reliefs'}],
    },
    {
      type: 'category',
      label: 'Watercolors',
      items: [{type: 'autogenerated', dirName: 'watercolors'}],
    },
  ],
};

export default sidebars;
