export interface Track {
  slug: string;
  title: string;
  description: string;
  src: string;
}

export const tracks: Track[] = [
  {
    slug: 'dream',
    title: 'A Dream Within a Dream',
    description: "This song is a musical interpretation of Edgar Allan Poe's evocative poem \"A Dream Within a Dream,\" featuring the vocals of Olha Volodina and the guitar accompaniment of Serhiy Zarudnyak. As the founder of the musical group \"Shkola Tantsiv\" and a recognized composer, Zarudnyak brings his distinct artistic vision to this collaboration.\n\nThe composition embodies several key elements of Zarudnyak's creative philosophy. Much like his visual art, Zarudnyak's music employs an economy of artistic means to achieve a polysemy of meaning — the sparse arrangement of voice and guitar allows the weight of Poe's existential questions to emerge from the darkness. The song explores the tragic essence of the human condition: the fleeting nature of time and reality. Zarudnyak considers tragicomedy his favorite genre because it reflects how life is always a mixture of the sad and the funny, a theme central to Poe's poem.\n\nThe choice of Poe's text aligns with Zarudnyak's belief that an artist must have a transcendent plane in mind. By questioning whether life is a \"dream within a dream,\" the song touches on the mystical experience that Zarudnyak strives to create in all his works. Zarudnyak also views traditional and folklore motifs as a breath of fresh air in the exhausted era of postmodernism — this adaptation of a classic literary work enriches a traditional structure with modern emotional depth.",
    src: '/audio/dream.mp3',
  },
  {
    slug: 'steamer',
    title: 'Steamer',
    description: "The musical composition \"Steamer\" (also titled \"И услышавши это...\") is a collaborative work featuring music composed by Serhiy Zarudnyak with vocals and guitar performance by Oleg Shynkarenko.\n\nThe song's lyrical foundation is drawn from the poem \"Fin de Siècle\" by the renowned poet Joseph Brodsky. The text expresses a sudden, profound desire to abandon mundane or exhausting labor — metaphorized as \"digging the earth\" — in favor of boarding a steamer to sail away.\n\nUnlike traditional voyages of exploration, the journey described is not intended to find new islands, plants, or new organisms in exotic latitudes — the purpose is exactly the opposite. The poem concludes with a cryptic and poignant focus on \"the mouth\" (главным образом — рот), which in the context of Brodsky's work often suggests a movement toward silence, the cessation of speech, or a purely internal realization. The track stands as a musical interpretation of classical intellectual poetry.",
    src: '/audio/steamer.mp3',
  },
  {
    slug: 'van-der-graaf',
    title: 'Van Der Graaf Generator',
    description: "The musical composition \"Van Der Graaf Generator\" is an Indie track recorded in 2002. The song features music adapted by Serhiy Zarudnyak from a vocal melody of a Bulgarian folk song performed by Penka Pavlova. The lyrics are an original work by Serhiy Zarudnyak, and the recording and arrangement were a collaborative effort between Zarudnyak and Oleg Shynkarenko. In this performance, the track features the vocals of Nastya Shylo and guitar by Oleh Shynkarenko.\n\nThe lyrics present a nostalgic and philosophical reflection on cultural legacy, memory, and the passage of time. The song opens by naming iconic progressive and post-punk bands — Van Der Graaf Generator, Siouxsie and the Banshees, and the Grateful Dead — characterizing them as things that have \"disappeared\" and \"are no longer here,\" framing the song as a meditation on a lost era of music and art.\n\nThe imagery of a truck delivering milk to children, who drink it and \"remember everything easily,\" suggests a simplified way in which the next generation consumes history, contrasted with the complex \"layouts\" of who was right or wrong. The text weaves in significant cultural markers: the phrase \"From Nowhere with Love\" (Ниоткуда с любовью) is a direct reference to a famous poem by Joseph Brodsky, while \"At the last breath\" (на последнем дыхании) mirrors the title of Jean-Luc Godard's seminal French New Wave film. The concluding lines focus on finding a \"secret\" guide through language and memory — art and culture as essential tools for navigating life's moral and physical crossroads.",
    src: '/audio/van.mp3',
  },
  {
    slug: 'wise-and-beautiful-girl',
    title: 'Wise and Beautiful Girl',
    description: "The musical composition \"Wise and Beautiful Girl\" is an Indie track featured on the SoundCloud platform. The song features music and lyrics by Serhiy Zarudnyak, and in this performance, the track features the vocals of Tetyana Levina and guitar by Oleh Shynkarenko.\n\nThe lyrics present a whimsical and minimalist reflection on the interplay between human intention and the unpredictability of the natural world. The song centers on a simple, repetitive decision-making process regarding the weather — \"if it rains, we won't go anywhere; if it doesn't, then we can go\" — framing the narrative as a meditation on domestic passivity and the simplicity of daily choice.\n\nThe central figure of the \"wise and beautiful girl\" (умница и красавица) provides a focal point for the track's internal logic; the lyrics suggest she possesses a discerning perspective, noting that she \"knows\" the situation and likely \"will not like it.\" The imagery of \"green grass\" (зеленая трава) serves as a grounding natural element, suggesting a quiet, perhaps pastoral setting where the small details of the environment dictate the flow of the day. The concluding lines reinforce a theme of gentle hesitation, where the potential for action remains entirely dependent on external forces, capturing a moment of quiet, suburban existentialism.",
    src: '/audio/girl.wav',
  },
  {
    slug: 'while-guys-are-dreaming',
    title: 'While Guys are Dreaming',
    description: "The musical composition \"While Guys are Dreaming\" is an Indie track with music and text by Serhiy Zarudnyak. In this arrangement, the track features the vocals of Tetyana Levina and computer programming by Oleh Shynkarenko.\n\nThe lyrics present a contemplative and atmospheric meditation on the suspension of time and the diverging paths of personal destiny. The song opens with a scene of nocturnal stillness — \"while the boys are sleeping\" — where \"nothing is happening,\" framing the narrative as a reflection on a moment of liminality and internal transition. The mention of a radio playing for \"20 years straight\" without ever becoming tiresome suggests a sense of cultural or personal endurance amidst a world that feels \"quiet and dark.\"\n\nThe imagery of \"trains carrying one away to freedom\" (поезда, увозящие на волю) and \"forgotten places\" evokes a deep sense of nostalgic longing and the search for an identity beyond the immediate surroundings. A central philosophical tension is introduced with the question \"Are we going the same way?\" and the definitive response: \"No, we are going in the other direction\" (Нет, мы в другую сторону). This rejection of a shared path highlights a theme of individual autonomy and the courage to depart from the collective. The composition concludes with the moon peering through the window and clouds moving toward the horizon, situating these private, human reflections within the vast and indifferent rhythm of the natural world.",
    src: '/audio/guys.wav',
  },
  {
    slug: 'tristesse',
    title: 'Tristesse',
    description: "The musical composition \"Tristesse\" is an Indie Pop track. The music composed by Serhiy Zarudnyak with lyrics written by Olha Volodina. In this rendition, the track features the vocals, guitar, and computer programming of Oleh Shynkarenko, who also handled the recording and rendering.\n\nThe lyrics, performed in French, present an intimate and melancholic meditation on the intersections of devotion, tenderness, and emotional reliance. The song opens with a poignant acknowledgement of \"sadness\" (tristesse), which is immediately countered by the joy of a loved one's presence. By addressing the subject as \"my mistress\" (ma maîtresse) and \"my tenderness\" (ma tendresse), the narrative characterizes the relationship as an essential emotional sanctuary, suggesting a state of profound vulnerability where the speaker \"has nothing\" without the other.\n\nThe imagery of a \"small sun between the hands\" (un petit soleil entre les mains) that \"expands\" serves as a central metaphor for the internal radiance and warmth generated by intimacy. This symbol of light represents a private, shared universe that defies the limitations of the external world. The concluding line, stating that \"there are no more paths that lead to its end\" (Il n'y a plus de chemins qui mènent à sa fin), elevates the sentiment to a level of philosophical infinity. It suggests that true emotional connection transcends linear time and finality, existing as a boundless state of being rather than a journey toward a destination.",
    src: '/audio/tristesse.wav',
  },
];
